#!/bin/bash

global
    log /dev/log    local0
    log /dev/log    local1 notice
    daemon
    maxconn 2048
    ssl-default-bind-options no-sslv3
    ssl-default-bind-ciphers PROFILE=SYSTEM

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend https_front
    bind *:443 ssl crt /etc/ssl/private/haproxy.pem
    mode http
    default_backend web_back

frontend http_front
    bind *:80
    redirect scheme https code 301 if !{ ssl_fc }

backend web_back
    mode http
    server web1 127.0.0.1:80 check


